const effects = {
  chrome: {
    class: 'effects__preview--chrome',
    id: 'effect-chrome',
    filter: 'grayscale',
    min : 0.1,
    max : 1,
    start: 1,
    step: 0.1,
    unit : '',
  },
  sepia: {
    class: 'effects__preview--sepia',
    id: 'effect-sepia',
    filter: 'sepia',
    min : 0.1,
    max : 1,
    start: 1,
    step: 0.1,
    unit : '',
  },
  marvin: {
    class: 'effects__preview--marvin',
    id: 'effect-marvin',
    filter: 'invert',
    min : 0,
    max : 100,
    start: 100,
    step: 1,
    unit : '%',
  },
  phobos: {
    class: 'effects__preview--phobos',
    id: 'effect-phobos',
    filter: 'blur',
    min : 0,
    max : 3,
    start: 3,
    step: 0.1,
    unit : 'px',
  },
  heat: {
    class: 'effects__preview--heat',
    id: 'effect-heat',
    filter: 'brightness',
    min : 1,
    max : 3,
    start: 3,
    step: 0.1,
    unit : '',
  },
};

export { effects };
